### ISSUE TITLE
Handling negative arguments with argparse

### ISSUE THREAD

**Issue by pbaylies** [ExplainableML/ReNO#1]
https://github.com/ExplainableML/ReNO/blob/172e9973be395db744f1869632a8b1ed0fcdb7a3/arguments.py#L41

Friendly note that for negative (action `store_false`) default arguments on the command line, I'd suggest handling it like so:

```parser.add_argument("--disable_hps", default=True, action="store_false", dest="enable_hps")```

That's because it's confusing to "enable" something on the command line and then have it end up disabled.

**Comment by sgk98** [comment]
Thanks for the suggestion! I have made the changes here a6a8b47. If you have any other suggestions/changes, please let us know, or feel free to make a pull request.
